### ISSUE TITLE
Add contribution guideline

### ISSUE THREAD

**Issue by cbordier** [Axway/agent-sdk#125]
We need to provide a `CONTRIBUTING.md` file explaining how to create good issue / pull request 

_Reference_: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

We should also include a link from the `README.md` to the `CONTRIBUTING.md` to help the community to find it.

# Suggested content:

The following is a set of guidelines for contributing to Agent SDK and its packages, which are hosted in the Axway Organization on GitHub. These are mostly guidelines, not rules. Use your best judgment, and feel free to propose changes to this document in a pull request.

### Contributing to Agent SDK

You are more than welcome to help us maintaining and suggesting improvements to this SDK.

#### Did you find a bug?

Before reporting a bug, ensure it is not already reported by searching on GitHub under [Issues](https://github.com/Axway/agent-sdk/issues).

When describing a bug, please use the following pattern:
* **Github issue title**: be as precise and clear as possible
*  Github issue content:
    * **step(s) for reproducing the issue**: explain the action(s) that lead to the issue
    * **current behavior**: describe what you see after the taken step(s)
    * **expected behavior**: describe what you expect

Then the bug will be triaged by Axway contributor and the correction process via pull request can start.

#### Did you write a patch that fixes a bug?

* Be sure to have thoroughly tested the patch in your environment **BEFORE** submitting the pull request.
* Open a new GitHub pull request with the patch.
* Ensure the pull request description clearly describes the problem and solution. Include the relevant issue number if applicable.
* The pull request will be reviewed by Axway contributor and merge accordingly.

#### Do you intend to add a new feature or change an existing one?

If you want to submit a new feature or improvement proposal, please open an issue which must include:

* Why do we need an improvement or new feature?: A detailed description of the problem at hand.
* How to solve the problem?: A proposal of how you would solve the problem.

The issue will be reviewed / approved or rejected by Axway contributors. Once an issue is approved, the issue will be placed in a 
 target delivery milestone.

#### Do you have questions about the Agent SDK?

Create an issue containing your question. Be sure to use the `question` label on the issue. The community will answer it in a timely manner.

### Getting started

In order to get familiar with Agent SDK, please read [Amplify Central Agents SDK](https://github.com/Axway/agent-sdk/blob/main/README.md).

**Comment by tsjohns9** [comment]
A contributing guide was just added to the mulesoft agents. I'll leave this here as a reference so we can try and keep our guidelines in sync. https://github.com/Axway/agents-mulesoft/blob/main/CONTRIBUTING.md
