### ISSUE TITLE
Modify Readme.md and contributing.md files to reflect official SDK name

### ISSUE THREAD

**Issue by rumelitandon** [Axway/agent-sdk#156]
In the SDK docs -  file (https://github.com/Axway/agent-sdk/blob/main/README.md & https://github.com/Axway/agent-sdk/blob/main/CONTRIBUTING.md) use the official name of the SDK which is “Amplify Agent SDK .

**Comment by xcorvelle** [comment]
Brand Central: https://axwaybrandcentral.axway.com/assets/287847

**Comment by tsjohns9** [comment]
The docs refer to the discovery agent as `Amplify Central Discovery Agents` and the traceability agent as `Amplify Central Traceability Agents`. Do these names need to be updated?

**Comment by rumelitandon** [comment]
> The markdown docs refer to the discovery agent as `Amplify Central Discovery Agents` and the traceability agent as `Amplify Central Traceability Agents`. Do these names need to be updated?

Not yet. Just focus on the references to the SDK for now.

**Comment by tsjohns9** [comment]
There are several readme files in this repo. All readme files should be updated to reflect the branding requirements when referring to the SDK.
