### ISSUE TITLE
Flag to turn off agent SDK version check job

### ISSUE THREAD

**Issue by mcollins-axway** [Axway/agent-sdk#227]
The latest agent SDK has a version checker in it. Looks like it assumes the agent is in the public jfrog. Our agent is not in the public space. We are unsure when/if it will be. Could we have a flag in the SDK to turn this feature off and thus avoid this trace in the agent log..
 
{"level":"error","msg":"could not create the agent version checker: [Error Code 1005] - empty or generic data plane type name. No version to compare for upgrade","time":"2021-10-22T12:19:13+01:00"}

**Comment by subhae** [comment]
Validated that  the trace agent version 1.1.5-f1ca23c0, Amplify Agents SDK version 1.1.8, disco agent - 1.1.5-2c823b38 have the flag to enable/disable the version checker. 
CENTRAL_VERSIONCHECKER set to true (default) would check for the latest version. When set to false, the check against the latest release is not done.
